### ISSUE TITLE
Display score tables as image

### ISSUE THREAD

**Issue by david1602** [david1602/1337#14]
The score table is kind of unaligned in text form. My idea is to generate a HTML page, render it, screenshot it and post the screenshot. This could be a function that receives an Array of Arrays and will render a table accordingly. The score function could use that.

For a library we could use https://github.com/brenden/node-webshot, which seems to fulfill our needs. The file must be deleted after it was posted.

**Comment by madr1c** [comment]
This has also now been implemented.
