### ISSUE TITLE
Streaks don't seem to work

### ISSUE THREAD

**Issue by david1602** [david1602/1337#8]
Currently it seems like streaks are not correctly recognized if two subsequent days contain posts.

**Comment by madr1c** [comment]
It's because your [date comparison](https://github.com/david1602/1337/blob/master/db.js#L156) fails.

You should try:
`if (records.length > 0 && moment(postdate).diff(moment(records[0].postdate), 'days') === 1)`

**Comment by david1602** [comment]
Fixed with your PR.
